#pragma once
namespace {
const char* SVM_MESSAGE = "{"
    "\"dataset\": \"59705aa8aa39d855e5678b50\","
    "\"datasource\": {"
            "\"path\": \"/home/boaz/work/machine_learinig_models/src/apps/run_experiments/ut/input.csv\""
    "},"
    "\"model\": {"
        "\"class\": \"five\","
        "\"type\": \"classifier\","
        "\"repeations\": 1"
    "},"
    "\"action\": {"
            "\"name\": \"model.svm\","
            "\"attr\": {"
                "\"termination-count\": 111,"
                "\"termination-epsilon\": 0.0001,"
                "\"kernel\": \"rbf\""
            "}"
    "},"
    "\"evaluation\": ["
        "\"auc-roc\", \"ks-test\""
    "],"
    "\"export\": {"
        "\"type\": \"yml\","
        "\"path\": \"/home/boaz/work/machine_learinig_models/src/apps/run_experiments/ut/model.yml\""
    "},"
    "\"validation\": {"
        "\"action\": \"precent\","
        "\"attr\": {"
            "\"arg\": 80"
        "}"
    "}"
"}";
const char* INVALID_SVM_MESSAGE = "{"
    "\"dataset\": \"59705aa8aa39d855e5678b50\","
    "\"datasource\": {"
            "\"path\": \"/home/boaz/work/machine_learinig_models/src/apps/run_experiments/ut/input.csv\""
    "},"
    "\"model\": {"
        "\"class\": \"five\","
        "\"type\": \"classifier\","
        "\"repeations\": 1"
    "},"
    "\"action\": {"
            "\"name\": \"model.svm\","
            "\"attr\": {"
                "\"termination-epsilon\": 0.0001"
            "}"
    "},"
    "\"evaluation\": ["
        "\"auc-roc\", \"ks-test\""
    "],"
    "\"export\": {"
        "\"type\": \"yml\","
        "\"path\": \"/home/boaz/work/machine_learinig_models/src/apps/run_experiments/ut/model.yml\""
    "},"
    "\"validation\": {"
        "\"action\": \"precent\","
        "\"attr\": {"
            "\"arg\": 80"
        "}"
    "}"
"}";
}
